# !- quest
# # - kill anybody
# @ - Location
# - - Doing something

ActOne = [
    "",
    "@The Twilight Strand",
    "#Kill Hillock",
    "@Lioneye's Watch",
    "!Enemy at the Gate (Tarkleigh)",
    "@Lioneye's Watch",
    "@The Coast",
    "-Get WP",
    "@The Mud Flats",
    "-Find 3 eggs",
    "@The Submerged Passage",
    "-Get WP",
    "!Breaking Some Eggs (Tarkleigh)",
    "@The Submerged Passage",
    "@The Flooded Depths",
    "#Kill The Dweller of the Deep",
    "!The Dweller of the Deep",
    "@The Ledge",
    "-Get WP",
    "@The Climb",
    "-Get WP",
    "@The Lower Prison",
    "-Get WP",
    "-Complete lab",
    "@The Upper Prison",
    "@The Wardens Quarters",
    "@The Wardens Chambers",
    "#Kill Brutus",
    "!The Caged Brute (Tarkleigh)",
    "-Prisoners Gate",
    "@The Ship Graveyard",
    "-Get WP",
    "@The Ship Graveyard Cave",
    "-Get AllFlame",
    "@The Ship Graveyard",
    "#Kill Fairgraves",
    "!The Marooned Mariner (Bestel)",
    "@The Cavern of Wrath",
    "-Get WP",
    "@The Cavern of Anger",
    "@Merveils Lair",
    "#Kill Mervel",
    "@The Southern Forest",
    "@The Forest Encampment",
    "",
]

ActsList = [ActOne,]